<?php

define('MAIN_MENU_CACHE_KEY','MAIN_MENU');
define('FOOTER_MENU_CACHE_KEY','FOOTER_MENU');
define('MOBILE_MENU_CACHE_KEY','MOBILE_MENU');
define('HOMEPAGE_CACHE_KEY','HOMEPAGE');
define('MIXES_CACHE_KEY','MIXES');
define('RELEASES_CACHE_KEY','RELEASES');
define('PLAYLISTS_CACHE_KEY','PLAYLISTS');
define('BIO_CACHE_KEY','BIO');
define('INTERNATIONAL_CACHE_KEY','INTERNATIONAL');
define('VIDEOS_CACHE_KEY','VIDEOS');
define('SOCIAL_CACHE_KEY','SOCIAL');
define('CONTACT_CACHE_KEY','CONTACT');
define('MODAL_CACHE_KEY', 'MODAL');
define('GALLERY_CACHE_KEY','GALLERY');
define('GALLERY_MOBILE_CACHE_KEY','GALLERY_MOBILE');
define('LINK_TREE_CACHE_KEY','LINK_TREE');

