version: '3.9'

volumes:
    logs:
        driver: local

services:
    backend:
        build: ./docker
        #image: diveinteractive/php81-alpine
        container_name: PHP
        working_dir: /var/www/public
        command: php -S 0.0.0.0:8080 -t ./
        environment:
            docker: "true"
        ports:
            - 5050:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - app-network

    frontend:
        build: ./docker
        #image: diveinteractive/php81-alpine
        container_name: PHP_HEAD
        working_dir: /var/www/public_html
        command: php -S 0.0.0.0:8080 -t ./
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - ../php8-headless:/var/www
            - logs:/var/www/logs
        networks:
            - app-network
                    
    mariadb:
        container_name: DB
        image: mariadb
        ports:
            - 4306:3306
        restart: always
        environment:
            MYSQL_DATABASE: djfabriz_headless
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge